export { default as Navbar } from "./Navbar";
export { default as Attendance } from "./Attendance";
export { default as Footer } from "./Footer";
export { default as ImportantAnnouncement } from "./ImportantAnnouncement";
export { default as JoiningAnniversarry } from "./JoiningAnniversarry";
export { default as LeaveCount } from "./LeaveCount";
export { default as Birthday } from "./Birthday";
export { default as Profile } from "./Profile";
export { default as ToggleSwitch } from "./ToggleSwitch";
